### PR TITLE
Update ModelCollection to use index types instead of extending Dictionary

### PR DESCRIPTION
**Pull request by tragessere**
This change should make directly accessing our ModelCollections a little less cumbersome with typing. By splitting the single index type into a number and a string index, accessing a ModelCollection with a number key will no longer include the Metadata type. The string index type is still included since we allow GUIDs as temporary keys at times, so those will still require type assertions to remove the Metadata type.

previous
```
const collection: ModelCollection<Group>
const foo = collection[1] // Group | Metadata | null | undefined
const bar = collection['abcd'] // Group | Metadata | null | undefined
```

now
```
const collection: ModelCollection<Group>
const foo = collection[1] // Group | null | undefined
const bar = collection['abcd'] // Group | Metadata | null | undefined
```

### CODE REVIEW

**Comment by tragessere** [comment]
Just pushed a change to keep ModelCollection as an interface instead of a type. I don't know why I was thinking that syntax required it to be a type.

**Comment by builtbywill** [comment]
@tragessere This seems to work ok

Aren't all JS object keys technically strings? Also we do use GUIDs for some object ids, like User related items.

I guess this is just saying any key that is "number-ish", we know will never be the `Metadata`, but if it a string it could be any of the options?

**Comment by tragessere** [comment]
Yeah, you're right on both of those. Typescript can still look at number keys for type-checking purposes, but in the end they are still turned into strings. 

And for those string ids and guids this should behave the same as before, so it is only helpful for actual number ids. I'm not sure if there's a better way to handle those string keys.

**Comment by builtbywill** [comment]
@tragessere fyi you should probably merge this to develop, or a release / hotfix branch?

**Comment by jkdufair** [comment]
This seems like a nice improvement. Thanks @tragessere

**Review by jkdufair — APPROVED** [review]

**Comment by jkdufair** [comment]
This seems like it could be an interesting approach to detecting UUIDs: https://spin.atomicobject.com/2018/01/15/typescript-flexible-nominal-typing/

**Comment by tragessere** [comment]
Whoops, meant to have this go to develop then make a release branch. Would a hotfix branch be ok too? I guess it would cut down on the git noise a bit

**Comment by builtbywill** [comment]
> Whoops, meant to have this go to develop then make a release branch. Would a hotfix branch be ok too? I guess it would cut down on the git noise a bit

@tragessere either way is fine 🤷 

probably going to need to update auth and scaffolding as well?

**Comment by gavin-brown** [comment]
Solid Typescript ninja change and thanks for the explanation!

**Comment by tragessere** [comment]
I switched it to develop. I can just make a release branch afterwards, no big deal.

I could update scaffolding after this, but did you have anything specific in mind for studiokit-auth? We don't use ModelCollection there.

**Pull request merged**
