### PR TITLE
Feature/parameters

### PR DESCRIPTION
**Pull request by camliu89**
Please review! :)

### CODE REVIEW

**Comment by gavin-brown** [comment]
You'll want to  👋 🚮 with the lib folder

**Comment by camliu89** [comment]
@gavin-brown should i delete the folder or just leave it there?

**Comment by gavin-brown** [comment]
@camliu89 Yeah you'll want to delete. Maybe we should add it to our .gitignore? Would that affect the npm publish?

**Comment by builtbywill** [comment]
@gavin-brown @camliu89 Since we don't have `lib` ignored on develop yet, you can hold off on it. I have deleted and ignored it in my new branch, so that change will get merged in when I close out mine.

**Comment by camliu89** [comment]
@builtbywill thanks! i will then merge this into develop?

**Pull request merged**
